apiVersion: v1
kind: Pod
metadata:
  name: payment-orchestrator
spec:
  containers:
  - name: payment-orchestrator
    image: localhost:32000/payment-orchestrator:0.0.1-SNAPSHOT
    imagePullPolicy: Always
    env:
    - name: BROKER_URL
      value: "rabbitmq-service"
